# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk17

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      - mez365@mail.ru
    on_success: never # default: change
    on_failure: always # default: always
env:

  global:

    - CODECOV_TOKEN="ea9af717-3522-4a34-b655-15d2c11c0519"